### ISSUE TITLE
Feature request: support multiple QR code configurations

### ISSUE THREAD

**Issue by gremo** [endroid/qr-code#74]
Hi there! Great library! What about moving the Symfony bundle in another package? In addition, I would add more configuration like this:

```yml
endroid_qr_code:
    my_qr1:
        size: 100
        padding: 10
        extension: gif
        error_correction_level: medium
        foreground_color: { r: 0, g: 0, b: 0, a: 0 }
        background_color: { r: 255, g: 255, b: 255, a: 0 }
        label: 'My label'
        label_font_size: 16
    myqr2:
        size: 250
        padding: 10
        error_correction_level: high
    # ...
```
```php
$this->get('endroid_qrcode.myqr2')->createQrCode();
```
